### ISSUE TITLE
Unexpected behavior when using .type.toBe with infer

### ISSUE THREAD

**Issue by olsonpm** [tstyche/tstyche#316]
I ran into unexpected behavior when using `expect<SomeType>().type.toBe<Itself>` with a function that infers a value in its result.

Here's the minimal code which throws the subsequent error

```ts
import { expect, test } from 'tstyche'

type TestInfer = <A extends Array<any>>(
  arr: A
) => A extends Array<infer V> ? V : unknown

test('error with identical types', () => {
  expect<TestInfer>().type.toBe<
    <A extends Array<any>>(arr: A) => A extends Array<infer V> ? V : unknown
  >()
})
```

> Error: Type '<A extends Array>(arr: A) => A extends (infer V)[] ? V : unknown' is not identical to type '<A extends Array>(arr: A) => A extends (infer V)[] ? V : unknown'.

I'm expecting the type to be itself.  I dug around for a little bit, seems you use typescript's `isTypeRelatedTo` to match exact types.  When I looked at the git history in typescript's repository I couldn't find what that function's purpose was, and my small amount of googling didn't return much.

[Here's a repository with reproduction steps](https://github.com/olsonpm/repro/tree/tstyche-infer-issue)

I can keep digging if you feel this is an issue in your library.

**Comment by mrazauskas** [comment]
Could you tell more what you are trying to test?

Te behaviour must be correct, because `.toBe()` simply picks up both types, passes them to TypeScript and reports back. In this case both types are left as is and TSTyche does nothing with types at all.

The test itself looks strange, because it does not check any behaviour of the type. I mean, there is nothing like with this input, expect that output. Or so. I understand this is just a dummy example. So what are you trying to test?

**Comment by olsonpm** [comment]
the test was simplified for sake of showing the unexpected error and narrowing down the cause.  I ran into this when testing a functional utility which infers the value of the parameter, where the value could be one of a few collection types e.g. array, record, set or map.  So my real test confirms the resulting function contains the expected parameter types based on input.

I'm not understanding your statement though

> The behaviour must be correct... TSTyche does nothing with types at all

If the behavior must be correct, why would tstyche report an error when the types are exactly the same and the editor doesn't report any errors ?  And if you saying that no function which infers a value in its result can use toBe, then how do you suggest testing such a type ?

**Comment by mrazauskas** [comment]
`.toBe()` is testing if types are identical. Might be I missed something, but most of the errors in code editors are about assignability. Or?

If you are about to test a generic function, take a look at very first example from [documentation](https://tstyche.org) (;

Here is simplified version of it:

```ts

import { expect } from "tstyche";

function firstItem<T>(target: Array<T>): T | undefined {
  return target[0];
}

expect(firstItem(["a", "b"])).type.toBe<string | undefined>();

expect(firstItem([1, 2, 3])).type.toBe<number | undefined>();
```

Focus on usage, not the internals.

**Comment by olsonpm** [comment]
> .toBe() is testing if types are identical

I appreciate your responses, but can you explain how the types in my example **aren't** identical ?  I think that's where I'm hung up

**Comment by mrazauskas** [comment]
TypeScript internals are sure that they are not. That’s it (;

**Comment by olsonpm** [comment]
Ha - I do appreciate it.  It's not that my code is private or that I mind sharing, it's the complexity of my types will cause more confusion than it's worth.  If .toBe doesn't work with inferred results then I'll use a different method.

**Comment by olsonpm** [comment]
For anyone who runs into this in the future - I realized a wrapper type for the infer operation works here.  e.g. the following code passes

```ts
import { expect, test } from 'tstyche'

type ArrayVal<A extends Array<any>> = A extends Array<infer V> ? V : never

type TestInfer = <A extends Array<any>>(arr: A) => ArrayVal<A>

test('error with identical types', () => {
  expect<TestInfer>().type.toBe<<A extends Array<any>>(arr: A) => ArrayVal<A>>()
})
```

I understand this code is contrived and that ideal approaches will vary per each developer's situation.  This worked in my situation because the inferred type was in fact a wrapper (i.e. an alias) - and my pattern of copy/pasting the expanded type in the tooltip could be simplified by using the aliases themselves.

**Comment by mrazauskas** [comment]
Good news: since TSTyche 6, the example in the OP can be tested without any workarounds.
