### ISSUE TITLE
Assignability matchers do not protect against `any` or `never`

### ISSUE THREAD

**Issue by mrazauskas** [tstyche/tstyche#367]
Currently `.toBeAssignableTo()` and `.toBeAssignableWith()` matchers do not protect against `any`, `never` or `unknown`.

Probably the source type should not be allowed to be `any`, `never` or `unknown`, because those are assignable to each and every type. That can lead to false positives easily. Like in this case with missing import:

```ts
import { expect } from "tstyche";

// @ts-expect-error
expect(missing()).type.toBeAssignableTo<string>(); // pass!
```

---

It does not make much sense to check, if `any`, `never` or `unknown` is assignable to / with something. If that’s the intent, one should explicitly use `.toBeAny()`, `.toBeNever()` or `.toBeUnknown()`.

---

I think the following cases should at least log a warning. Here the target type can be whatever and assertions will pass. Always passing assertion sounds like a bug.

```ts
import { expect } from "tstyche";

expect<any>().type.toBeAssignableTo<{ a: number }>();
expect<never>().type.toBeAssignableTo<{ a: number }>();

expect<unknown>().type.not.toBeAssignableTo<{ a: number }>();

expect<{ a: number }>().type.toBeAssignableTo<any>();
expect<{ a: number }>().type.toBeAssignableTo<unknown>();

expect<{ a: number }>().type.not.toBeAssignableTo<never>();

///

expect<any>().type.toBeAssignableWith<{ a: number }>();
expect<unknown>().type.toBeAssignableWith<{ a: number }>();

expect<never>().type.not.toBeAssignableWith<{ a: number }>();

expect<{ a: number }>().type.toBeAssignableWith<any>();
expect<{ a: number }>().type.toBeAssignableWith<never>();

expect<{ a: string }>().type.not.toBeAssignableWith<unknown>();
```

---

Somewhat similar to [`no-unnecessary-condition`](https://typescript-eslint.io/rules/no-unnecessary-condition) rule.

**Comment by SerkanSipahi** [comment]
> Probably the source type should not be allowed to be any, never or unknown

This is a good idea because I have test cases where the first expect just checks whether the source type is not any or never!

Examle
```
it('.....', () => {
   expect<SomType>().type.not.toBe<any>();
   expect<...
   expect<...
});
...

**Comment by mrazauskas** [comment]
Indeed. By the way, `.toHaveProperty()` and other matchers do protect against `any` or `never`. Assignability matchers are the only ones that do not.

**Comment by SerkanSipahi** [comment]
> By the way, .toHaveProperty() and other matchers do protect against any or never

Didnt know that. I did it as protection.
